include:
  - board: nice_nano_v2
    shield: silakka54_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: silakka54_left_studio
  - board: nice_nano_v2
    shield: silakka54_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: silakka54_right_studio
